# Generated by Django 4.2.1 on 2023-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_answer_course_enrollment_module_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='email',
            field=models.EmailField(default='goziennabuife@yahoo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='name',
            field=models.CharField(default='goziennabuife@yahoo.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='phone',
            field=models.CharField(default='080736728292', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='profession',
            field=models.CharField(choices=[('Cardiac nurse', 'Cardiac Nurse'), ('Cardiology Registra', 'Cardiology Registra'), ('Cardiac Physiologist', 'Cardiac Physiologist'), ('Radiographer', 'Radiographer'), ('Student Nurse', 'Student Nurse'), ('Medical Student', 'Medical Student'), ('Student Physiologist', 'Student Physiologist'), ('Student Radiographer', 'Student Radiographer')], default='Cardiac Nurse', max_length=50),
            preserve_default=False,
        ),
    ]
