# Generated by Django 4.2.1 on 2023-08-04 18:09

from django.db import migrations


def link_enrollments_to_modules(apps, schema_editor):
    Enrollment = apps.get_model('academy', 'Enrollment')
    Module = apps.get_model('academy', 'Module')

    for enrollment in Enrollment.objects.all():
        # Assuming each enrollment has only one course, and the course has only one module
        module = Module.objects.filter(course=enrollment.course).first()
        if module:
            enrollment.module = module
            enrollment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_enrollment_email_enrollment_name_enrollment_phone_and_more'),
    ]

    operations = [
        migrations.RunPython(link_enrollments_to_modules),
    ]
