# Generated by Django 4.2.1 on 2023-08-10 21:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0005_enrollment_module_alter_module_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="video_height",
            field=models.PositiveIntegerField(default=360),
        ),
        migrations.AddField(
            model_name="module",
            name="video_width",
            field=models.PositiveIntegerField(default=640),
        ),
        migrations.AlterField(
            model_name="module",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="video"
            ),
        ),
    ]
