# Generated by Django 4.2.1 on 2023-06-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
