# Generated by Django 4.2.1 on 2023-09-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_remove_patient_user_patient_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="clincian",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="clincian",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
