# Generated by Django 4.2.1 on 2023-10-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_clincian_description_clincian_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="year",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="clincian",
            name="email",
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
