# Generated by Django 4.2.1 on 2024-01-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("client_email", models.EmailField(max_length=254)),
                ("date_of_appointment", models.DateField()),
                ("time_of_appointment", models.TimeField()),
                (
                    "reason_for_appointment",
                    models.CharField(
                        choices=[
                            ("Chest Pain", "Chest Pain"),
                            ("Palpitations", "Palpitations"),
                            ("Breathlessness", "Breathlessness"),
                            ("Feeling Dizzy", "Feeling Dizzy"),
                            ("Fatigue", "Fatigue"),
                            ("Swollen Limbs", "Swollen Limbs"),
                            ("Neck Pain", "Neck Pain"),
                            ("Jaw Pain", "Jaw Pain"),
                            ("Throat Pain", "Throat Pain"),
                            ("Upper Belly Pain", "Upper Belly Pain"),
                            ("Back Pain", "Back Pain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("other_symptoms", models.TextField(blank=True)),
                ("additional_notes", models.TextField(blank=True)),
            ],
        ),
    ]
