# Generated by Django 4.2.1 on 2023-07-03 21:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carecardioblog', '0002_rename_categoty_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='blog_02.jpg', max_length=255, verbose_name='image'),
        ),
    ]
