vscode:
  extensions:
    - esbenp.prettier-vscode
    - ms-python.python
    - dbaeumer.vscode-eslint

tasks:
  - name: Install Django and allauth
    init: |
      pip install Django allauth

  - name: Start Django server
    command: carecardio
